# Generated by Django 4.2.20 on 2026-05-23 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='cast',
            field=models.TextField(blank=True, null=True, verbose_name='بازیگران (با کاما جدا کنید)'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور سازنده'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='product',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='کارگردان'),
        ),
        migrations.AddField(
            model_name='product',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دانلود'),
        ),
        migrations.AddField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/', verbose_name='فایل دانلود'),
        ),
        migrations.AddField(
            model_name='product',
            name='download_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک دانلود'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان (دقیقه)'),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ژانر'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='فارسی', max_length=100, verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='پوستر'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='product',
            name='storyline',
            field=models.TextField(blank=True, null=True, verbose_name='خلاصه داستان'),
        ),
        migrations.AddField(
            model_name='product',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تریلر'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AddField(
            model_name='product',
            name='writer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pname',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weighted_rating',
            field=models.FloatField(default=0.0, verbose_name='امتیاز وزندار'),
        ),
    ]
