# Generated by Django 4.2.20 on 2026-05-24 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_alter_product_options_product_cast_product_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن')),
                ('status', models.CharField(choices=[('watching', 'در حال تماشا'), ('completed', 'تماشا شده'), ('planning', 'بعداً می\u200cبینم'), ('favorite', 'علاقه\u200cمندی')], default='planning', max_length=20, verbose_name='وضعیت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='App.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لیست تماشا',
                'verbose_name_plural': 'لیست\u200cهای تماشا',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
