# Generated by Django 4.2.20 on 2026-05-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='مثلاً 8.8', max_digits=3, null=True, verbose_name='امتیاز IMDb'),
        ),
        migrations.AddField(
            model_name='product',
            name='metacritic_score',
            field=models.IntegerField(blank=True, help_text='مثلاً 85', null=True, verbose_name='نمره متاکریتیک'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveSmallIntegerField(verbose_name='شماره فصل')),
                ('episode_count', models.PositiveSmallIntegerField(verbose_name='تعداد قسمت\u200cها')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='امتیاز IMDb فصل')),
                ('series', models.ForeignKey(limit_choices_to={'category__name': 'سریال'}, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='App.product')),
            ],
            options={
                'verbose_name': 'فصل سریال',
                'verbose_name_plural': 'فصل\u200cهای سریال',
                'ordering': ['series__Pname', 'season_number'],
                'unique_together': {('series', 'season_number')},
            },
        ),
    ]
